<a href="https://colab.research.google.com/github/Imaspson/PyTorchLearning/blob/main/00_PyTorch_Fundamentals_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a random tensor with shape `(7, 7)`

In [1]:
import torch


In [2]:
rand_tensor = torch.rand(7, 7)
rand_tensor

tensor([[0.3923, 0.0073, 0.7587, 0.0053, 0.2214, 0.9827, 0.6858],
        [0.1021, 0.1389, 0.1126, 0.4894, 0.2124, 0.0908, 0.6699],
        [0.1467, 0.5600, 0.1059, 0.8423, 0.7321, 0.5696, 0.0738],
        [0.1564, 0.6991, 0.0601, 0.9842, 0.0550, 0.1876, 0.6447],
        [0.9033, 0.3530, 0.4508, 0.8307, 0.6374, 0.3191, 0.9053],
        [0.3643, 0.9614, 0.4697, 0.4123, 0.1519, 0.8451, 0.3092],
        [0.7424, 0.0072, 0.6939, 0.2602, 0.8691, 0.5077, 0.7048]])

Perform a matrix multiplication on the tensor above with another tensor with shape `(1, 7)`

In [3]:
second_rand_tensor = torch.rand(1, 7)
second_rand_tensor.shape

torch.Size([1, 7])

In [4]:
transposed_second_tensor = second_rand_tensor.T
transposed_second_tensor

tensor([[0.2282],
        [0.5841],
        [0.7055],
        [0.4686],
        [0.9688],
        [0.3404],
        [0.9621]])

In [5]:
result = torch.matmul(rand_tensor, transposed_second_tensor)
result

tensor([[1.8403],
        [1.2944],
        [1.8042],
        [1.6851],
        [2.7167],
        [1.9015],
        [2.4780]])

Set the random seed to `0` and do exercises 2 & 3 again

In [10]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
first_one = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
second_one = torch.rand(1, 7)

transposed_second_one = second_one.T
new_res = torch.matmul(first_one, transposed_second_one)
new_res


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])