<a href="https://colab.research.google.com/github/Imaspson/PyTorchLearning/blob/main/00_PyTorch_Fundamentals_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a random tensor with shape `(7, 7)`

In [1]:
import torch


In [2]:
rand_tensor = torch.rand(7, 7)
rand_tensor

tensor([[0.2476, 0.2434, 0.5192, 0.9685, 0.8151, 0.6061, 0.8335],
        [0.9197, 0.1981, 0.3847, 0.0237, 0.1416, 0.2539, 0.3802],
        [0.4734, 0.7870, 0.6078, 0.9714, 0.9909, 0.6567, 0.9345],
        [0.6916, 0.8012, 0.6874, 0.8097, 0.3841, 0.8634, 0.7924],
        [0.4379, 0.4349, 0.2765, 0.5945, 0.3624, 0.3489, 0.9443],
        [0.9783, 0.7965, 0.3143, 0.7570, 0.7353, 0.3765, 0.0717],
        [0.2041, 0.1054, 0.7945, 0.2780, 0.8987, 0.2834, 0.8979]])

Perform a matrix multiplication on the tensor above with another tensor with shape `(1, 7)`

In [3]:
second_rand_tensor = torch.rand(1, 7)
second_rand_tensor.shape

torch.Size([1, 7])

In [4]:
transposed_second_tensor = second_rand_tensor.T
transposed_second_tensor

tensor([[0.5560],
        [0.8814],
        [0.4196],
        [0.5507],
        [0.7254],
        [0.3013],
        [0.0088]])

In [5]:
result = torch.matmul(rand_tensor, transposed_second_tensor)
result

tensor([[1.8846],
        [1.0429],
        [2.6716],
        [2.3707],
        [1.4465],
        [2.4422],
        [1.4380]])

Set the random seed to `0` and do exercises 2 & 3 again

In [6]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
first_one = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
second_one = torch.rand(1, 7)

transposed_second_one = second_one.T
new_res = torch.matmul(first_one, transposed_second_one)
new_res


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the gpu random seed)

In [14]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [18]:
torch.manual_seed(1234)
t1 = torch.rand(2, 3)
t1 = t1.to(device)

torch.manual_seed(1234)
t2 = torch.rand(2, 3)
t2 = t2.to(device)

In [19]:
t1.device, t2.device

(device(type='cuda', index=0), device(type='cuda', index=0))

Perform a matrix multiplication on the tensors you created

In [20]:
t2 = t2.T
t2

tensor([[0.0290, 0.3666],
        [0.4019, 0.0583],
        [0.2598, 0.7006]], device='cuda:0')

In [21]:
result = torch.matmul(t1, t2)
result

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

Find the maximum and minimum values of the output of 7

In [25]:
maximum = torch.max(result)
maximum

tensor(0.6287, device='cuda:0')

In [24]:
minimum = torch.min(result)
minimum

tensor(0.2161, device='cuda:0')

Find the maximum and minimum index values of the output of 7

In [26]:
max_index = torch.argmax(result)
max_index

tensor(3, device='cuda:0')

In [27]:
min_index = torch.argmin(result)
min_index

tensor(1, device='cuda:0')

Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)` Set the seed to `7` when you create it and print out the first tensor and its shape as well as the second tensor and its shape.

In [32]:
torch.manual_seed(7)
t = torch.rand(1, 1, 1, 10)
t, t.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [41]:
t_squeezed = t.squeeze()
t_squeezed, t_squeezed.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))