<a href="https://colab.research.google.com/github/Imaspson/PyTorchLearning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Indroduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12]])

In [16]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 4, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`
Start with random numbers -> Look at data -> update random numbers -> Look at data -> update random numbers
`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html


In [19]:
# Create a random tensor of size/shape (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3275, 0.2265, 0.7932, 0.6641],
        [0.3149, 0.9550, 0.9708, 0.9684],
        [0.8085, 0.5035, 0.4799, 0.9838]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
another_random_tensor = torch.rand(100, 100, 100)
another_random_tensor.shape, another_random_tensor.ndim

(torch.Size([100, 100, 100]), 3)

### Zeros and ones

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [27]:
# Use torch.range() deprecated
torch.range(0, 10)

<ipython-input-27-008256105807>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# Use torch.arange() more modern
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
torch.arange(start=1, end=11, step=1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
r = torch.arange(4, 1400, 10)
r

tensor([   4,   14,   24,   34,   44,   54,   64,   74,   84,   94,  104,  114,
         124,  134,  144,  154,  164,  174,  184,  194,  204,  214,  224,  234,
         244,  254,  264,  274,  284,  294,  304,  314,  324,  334,  344,  354,
         364,  374,  384,  394,  404,  414,  424,  434,  444,  454,  464,  474,
         484,  494,  504,  514,  524,  534,  544,  554,  564,  574,  584,  594,
         604,  614,  624,  634,  644,  654,  664,  674,  684,  694,  704,  714,
         724,  734,  744,  754,  764,  774,  784,  794,  804,  814,  824,  834,
         844,  854,  864,  874,  884,  894,  904,  914,  924,  934,  944,  954,
         964,  974,  984,  994, 1004, 1014, 1024, 1034, 1044, 1054, 1064, 1074,
        1084, 1094, 1104, 1114, 1124, 1134, 1144, 1154, 1164, 1174, 1184, 1194,
        1204, 1214, 1224, 1234, 1244, 1254, 1264, 1274, 1284, 1294, 1304, 1314,
        1324, 1334, 1344, 1354, 1364, 1374, 1384, 1394])

In [32]:
ones_r = torch.ones_like(input=r)
ones_r, ones_r.shape, ones_r.ndim

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 torch.Size([140]),
 1)

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning.
1. Tensors not right data type
2. Tensors not right shape
3. Tensors not on right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [33]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # wether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
complex_64_tensor = torch.rand(size=(3,3), dtype=torch.complex64)
complex_64_tensor

tensor([[0.4135+0.4573j, 0.7632+0.0180j, 0.6456+0.2642j],
        [0.6600+0.9027j, 0.0240+0.8531j, 0.2136+0.1828j],
        [0.2902+0.3583j, 0.9246+0.1001j, 0.4775+0.7707j]])

In [38]:
float_32_tensor * complex_64_tensor

tensor([[1.2404+1.3720j, 4.5793+0.1080j, 5.8103+2.3774j],
        [1.9800+2.7081j, 0.1439+5.1186j, 1.9223+1.6449j],
        [0.8705+1.0750j, 5.5474+0.6005j, 4.2979+6.9362j]])

In [39]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [40]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right data type - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor we use tensor.shape
3. Tensors not on right device - to get device from a tensor we use tensor.device

In [41]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5418, 0.1692, 0.9753, 0.1173],
        [0.7264, 0.5289, 0.0456, 0.4734],
        [0.2073, 0.7762, 0.5742, 0.0326]])

In [42]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5418, 0.1692, 0.9753, 0.1173],
        [0.7264, 0.5289, 0.0456, 0.4734],
        [0.2073, 0.7762, 0.5742, 0.0326]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [43]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplications in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

In [48]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [49]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 243 µs, sys: 0 ns, total: 243 µs
Wall time: 250 µs


tensor(14)

In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 37 µs, sys: 6 µs, total: 43 µs
Wall time: 45.5 µs


tensor(14)

One of the most common erros in deep learning: shape errors.
# There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner** dimensions must match.
2. The resultin matrix has the shape of the outer dimensions.

In [53]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 2))

tensor([[0.9399, 0.8161],
        [0.3574, 0.3467],
        [0.5560, 0.5658]])

In [54]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B.T).shape # torch.mm is the same as torch.matmul

torch.Size([3, 3])

In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [57]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


## Tensor aggregation: Finding the min, max, sum, mean etc

In [58]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [59]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [60]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [61]:
# Find the mean - the torch.mean funcion requires a tensor of float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [63]:
# Find the position - index of the max emelent
torch.argmax(x)

tensor(9)

In [64]:
# Find the position - index of the minimum element
torch.argmin(x)

tensor(0)

# Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vertical stack - vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [65]:
# Lets's create a tensor
import tensorflow as tf
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [66]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [67]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [68]:
# Changing z changes x ( because a view of a tensor shares the same memory with the original tensor)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [69]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x_reshaped.shape

torch.Size([1, 9])

In [71]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x_reshaped.squeeze().shape

torch.Size([9])

In [73]:
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [74]:
# torch.unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adds an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [75]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 to 1 1 to 2 and 2 to 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # color channel height width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [76]:
x_original[0, 0, 0] = 1
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(1.), tensor(1.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [77]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [80]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [81]:
x[0][2][2]

tensor(9)

In [82]:
# You can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [83]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [84]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [85]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [86]:
x, x[0, 2, 2], x[0, :, 2]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor(9),
 tensor([3, 6, 9]))

In [87]:
z = torch.arange(3)
for i in range(3):
  z[i] = x[0, i, i]
z

tensor([1, 5, 9])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [88]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [90]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [92]:
# Change the tensor, what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

* In short how a NN learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and pytorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [93]:
torch.rand(3, 3)

tensor([[0.0658, 0.0998, 0.1276],
        [0.9904, 0.7981, 0.1468],
        [0.6764, 0.8290, 0.1856]])

In [94]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6737, 0.8501, 0.5188, 0.8169],
        [0.6388, 0.2883, 0.3470, 0.8229],
        [0.6093, 0.8820, 0.2927, 0.1166]])
tensor([[0.2091, 0.7520, 0.0718, 0.0635],
        [0.0800, 0.4663, 0.8312, 0.0367],
        [0.0613, 0.5142, 0.1521, 0.2970]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# Let's make some random but reproducible tensors
# Set the random seed

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources: https://pytorch.org/docs/stable/notes/randomness.html

## Running tensors and PyTorch objects on the GPUs (and making faster cpmputations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes

Getting a GPU

Easiest - Use Google Colab for a free GPU (options to upgrade as well)
Use your own GPU = takes a little bit of setup and requires the investment of buying a gpu.
Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and acces them.

In [96]:
# Setup device-agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [97]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU

The reason we want tensors and models on our GPU is because a GPU results in faster computations.

In [98]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [99]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

### 4. Moving tensors back to the CPU

In [104]:
# If tensor is on GPU, can't transform it to NumPy

tensor_on_gpu.cpu().numpy() # -> coded so that it is no error, the original code was `tensor_on_gpu.numpy()`

array([1, 2, 3])

In [102]:
# To fix the GPU tensor with NumPy issue, we can first set it on the CPU

tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])