<a href="https://colab.research.google.com/github/Imaspson/PyTorchLearning/blob/main/01_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.1.0+cu118'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

# Convert scalar from `torch.Tensor` type to integer

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.6275, 0.0247, 0.6476, 0.0010],
         [0.0762, 0.6051, 0.1031, 0.9338],
         [0.0756, 0.7878, 0.5790, 0.8697]]),
 torch.float32,
 torch.Size([3, 4]))

In [20]:
# Create a random tensor of size (224, 224, 3)
random_tensor = torch.rand(size=(224, 224, 3))
random_tensor

tensor([[[0.9289, 0.1445, 0.6574],
         [0.0146, 0.5076, 0.3897],
         [0.3652, 0.7087, 0.6063],
         ...,
         [0.2529, 0.9690, 0.2119],
         [0.9668, 0.4157, 0.7515],
         [0.8255, 0.6434, 0.3248]],

        [[0.4370, 0.8064, 0.8989],
         [0.5618, 0.1624, 0.9115],
         [0.7847, 0.3818, 0.8701],
         ...,
         [0.9022, 0.7681, 0.3907],
         [0.2999, 0.0845, 0.2878],
         [0.0127, 0.7979, 0.9146]],

        [[0.2213, 0.9907, 0.4535],
         [0.1975, 0.0568, 0.2227],
         [0.7876, 0.1837, 0.3817],
         ...,
         [0.9547, 0.2543, 0.7035],
         [0.8790, 0.0312, 0.2884],
         [0.1896, 0.0752, 0.2943]],

        ...,

        [[0.7218, 0.5805, 0.5715],
         [0.7627, 0.1761, 0.9691],
         [0.6509, 0.8256, 0.4193],
         ...,
         [0.4081, 0.0883, 0.3361],
         [0.8192, 0.5243, 0.4593],
         [0.5530, 0.3796, 0.7997]],

        [[0.4101, 0.3823, 0.7213],
         [0.7572, 0.5776, 0.3817],
         [0.

In [22]:
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones_tensor = torch.ones(size=(3, 4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
rng = torch.arange(0, 11, 2)
rng

tensor([ 0,  2,  4,  6,  8, 10])

In [29]:
X = torch.zeros_like(rng)
X

tensor([0, 0, 0, 0, 0, 0])

In [30]:
Y = torch.ones_like(rng)
Y

tensor([1, 1, 1, 1, 1, 1])

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Details
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.1999, 0.5566, 0.7687, 0.1795],
        [0.9730, 0.2929, 0.5383, 0.5740],
        [0.8101, 0.8404, 0.3248, 0.5910]])
Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device of the tensor: cpu


In [35]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
tensor.add(10)

tensor([11, 12, 13])

In [41]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [43]:
tensor * tensor, torch.matmul(tensor, tensor)

(tensor([1, 4, 9]), tensor(14))

In [44]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)


RuntimeError: ignored

In [45]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [46]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [48]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [49]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [50]:
tensor = torch.arange(0, 101, 10)
tensor, tensor.argmin(), tensor.argmax()

(tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]),
 tensor(0),
 tensor(10))

In [51]:
tensor.dtype

torch.int64

In [54]:
tensor_int_32 = tensor.type(dtype=torch.int32)

In [56]:
# Create a tensor
x = torch.arange(1, 11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [62]:
x_reshaped = x.reshape(2, 5)
x_reshaped

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [63]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Previous shape: torch.Size([2, 5])

New tensor: tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
New shape: torch.Size([2, 5])


In [64]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
Previous shape: torch.Size([2, 5])

New tensor: tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])
New shape: torch.Size([1, 2, 5])


In [65]:
x_original = torch.rand(size=(224, 224, 3))
x_original

tensor([[[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588],
         ...,
         [0.5697, 0.2088, 0.6539],
         [0.3397, 0.9565, 0.0660],
         [0.3421, 0.0172, 0.3031]],

        [[0.6576, 0.9813, 0.5840],
         [0.9902, 0.5978, 0.7888],
         [0.9008, 0.9180, 0.2201],
         ...,
         [0.5322, 0.8510, 0.4556],
         [0.1844, 0.8533, 0.5698],
         [0.3568, 0.1704, 0.6172]],

        [[0.0231, 0.6317, 0.7472],
         [0.0614, 0.1727, 0.1405],
         [0.9203, 0.9251, 0.5313],
         ...,
         [0.4989, 0.0933, 0.3064],
         [0.6272, 0.5955, 0.8636],
         [0.8345, 0.2273, 0.2865]],

        ...,

        [[0.3599, 0.1989, 0.5711],
         [0.5387, 0.1378, 0.9763],
         [0.5521, 0.6004, 0.1658],
         ...,
         [0.1790, 0.9954, 0.6617],
         [0.9871, 0.5877, 0.7375],
         [0.1551, 0.7881, 0.3759]],

        [[0.7442, 0.8621, 0.7548],
         [0.6381, 0.0106, 0.0893],
         [0.

In [66]:
x_permuted = x_original.permute(2, 0 , 1)
x_permuted

tensor([[[0.2666, 0.4414, 0.1053,  ..., 0.5697, 0.3397, 0.3421],
         [0.6576, 0.9902, 0.9008,  ..., 0.5322, 0.1844, 0.3568],
         [0.0231, 0.0614, 0.9203,  ..., 0.4989, 0.6272, 0.8345],
         ...,
         [0.3599, 0.5387, 0.5521,  ..., 0.1790, 0.9871, 0.1551],
         [0.7442, 0.6381, 0.6170,  ..., 0.3450, 0.9618, 0.6393],
         [0.1369, 0.6237, 0.2424,  ..., 0.1167, 0.2933, 0.0992]],

        [[0.6274, 0.2969, 0.2695,  ..., 0.2088, 0.9565, 0.0172],
         [0.9813, 0.5978, 0.9180,  ..., 0.8510, 0.8533, 0.1704],
         [0.6317, 0.1727, 0.9251,  ..., 0.0933, 0.5955, 0.2273],
         ...,
         [0.1989, 0.1378, 0.6004,  ..., 0.9954, 0.5877, 0.7881],
         [0.8621, 0.0106, 0.3402,  ..., 0.6359, 0.7925, 0.7158],
         [0.4302, 0.8480, 0.8264,  ..., 0.1133, 0.5889, 0.3078]],

        [[0.2696, 0.8317, 0.3588,  ..., 0.6539, 0.0660, 0.3031],
         [0.5840, 0.7888, 0.2201,  ..., 0.4556, 0.5698, 0.6172],
         [0.7472, 0.1405, 0.5313,  ..., 0.3064, 0.8636, 0.

In [67]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'